CREATE DATABASE IF NOT EXISTS db_sis;

USE db_sis;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(250) NOT NULL,
	email VARCHAR(250) UNIQUE NOT NULL,
	password VARCHAR(250) UNIQUE NOT NULL
);
SHOW TABLES;
DESCRIBE users;